Enhance code style with prettier
profilecity/vidur pull request #108
Opened 2024-08-30 06:19 UTC by shivam-sharma7

- This https://github.com/profilecity/vidur/commit/f98270afd04dfea3562cb3c180db0b2e7ad4094c commit reffers to config of prettier and 
- This https://github.com/profilecity/vidur/commit/a5e414f9ef54e2a6d674b4a89074e173ae0e6472 commit reffers to latest code style depend on `.prettierrc` file.

- fixes: #94 

Also, now it would format only edited file if you run `npm run format` otherwise it won't, this is why i formatted codebase in this commit https://github.com/profilecity/vidur/commit/a5e414f9ef54e2a6d674b4a89074e173ae0e6472

2024-08-30 09:45 UTC, amandesai01 commented
That's amazing, do that! thanks!

2024-08-30 09:46 UTC, amandesai01 commented
Don't format files in this PR

2024-08-30 17:17 UTC, shivam-sharma7 commented
> Don't format files in this PR

Done

2024-08-30 17:25 UTC, amandesai01 commented
Also add post commit hook

2024-08-31 09:59 UTC, shivam-sharma7 commented
> Also add post commit hook

I think you want to add `pre-commit` hook as we have discussed in https://github.com/profilecity/vidur/issues/94#issuecomment-2298672349

2024-08-31 13:13 UTC, shivam-sharma7 commented
> Don't format files in this PR

Remember once this PR get merged then whenever you will change files or doing some work then when you try to commit those changes then it will format that file but also format unformatted file. Attention this is why I have formatted all because once all codebase follow our new rule then it will not change randomly, this will change only files that has changed by you or someone..

2024-09-02 11:56 UTC, shivam-sharma7 commented
@amandesai01 Now your changes in `main` branch, you can merge this

2024-09-02 14:17 UTC, amandesai01 commented
It's still undoing my changes, see package.json. The release command is getting deleted.

2024-09-03 01:11 UTC, shivam-sharma7 commented
> It's still undoing my changes, see package.json. The release command is getting deleted.

got it, check now

2024-09-03 10:16 UTC, amandesai01 requested changes

2024-09-03 10:16 UTC, amandesai01 commented on package.json
> +
```suggestion
```

2024-09-03 10:17 UTC, amandesai01 commented
Done, will merge in some time.

2024-09-03 10:20 UTC, amandesai01 commented
Can we have github action too in this PR?

2024-09-03 14:59 UTC, shivam-sharma7 commented
> Can we have github action too in this PR?

I have another issue and why i have this please check here -https://github.com/profilecity/vidur/issues/109#issuecomment-2322934715

2024-09-04 19:19 UTC, amandesai01 approved these changes

2024-09-04 19:20 UTC, merged