feat: 404 Fallback when jobs not found
profilecity/vidur pull request #169
Opened 2024-09-18 15:30 UTC by shivam-sharma7

This job posting is either revoked or URL is incorrect.

refference-> https://nuxt.com/docs/getting-started/error-handling

fixes: #6

2024-09-19 05:56 UTC, amandesai01 requested changes

2024-09-19 05:56 UTC, amandesai01 commented on app/error.vue
> +import { Icon } from '@iconify/vue';
This should not be imported, see usage of `NuxtIcon` throughout codebase.

2024-09-19 05:56 UTC, amandesai01 commented on package.json
> +    "@iconify/vue": "^4.1.2",
You don't need this dependency. We already have that.

2024-10-21 06:16 UTC, shivam-sharma7 commented
@amandesai01 can we merge it?

2025-01-30 16:00 UTC, amandesai01 approved these changes

2025-01-30 16:01 UTC, merged