UI: update vidur version in side navbar
profilecity/vidur pull request #171
Opened 2024-09-21 19:39 UTC by suryanshsoni120

Update vidur version in plateform side navbar.
fixes #170

2024-09-24 16:16 UTC, amandesai01 commented
@suryanshsoni120, you available for this?

2024-09-28 15:20 UTC, suryanshsoni120 commented
yes @amandesai01

2024-09-29 13:34 UTC, amandesai01 requested changes

2024-09-30 13:38 UTC, shivam-sharma7 commented
@suryanshsoni120 are you working on this?

2024-10-01 11:20 UTC, amandesai01 approved these changes

2024-10-01 11:21 UTC, merged