Docker File
profilecity/vidur pull request #24
Opened 2024-08-01 04:53 UTC by akashvarun10

This pull request adds Docker support for the Vidur application with a Dockerfile and Docker Compose setup. It configures the application and PostgreSQL database, ensuring automated builds and data persistence. Use `docker compose up --build` to start the services.

2024-08-01 04:54 UTC, akashvarun10 commented
I will be working on adding for production version of docker, once the app is ready..

2024-08-01 05:35 UTC, amandesai01 commented
We don't want to send .env file in docker, we can just use docker-compose to set the env variables

2024-08-01 06:29 UTC, akashvarun10 commented
If we use `localhost` reference in the `docker-compose.yml` is incorrect for `inter-container communication`. Within Docker, containers communicate using service names defined in Docker Compose. Using db instead of localhost ensures that the app container correctly resolves and connects to the db container.

And since this setup is only for development and not production, this approach should be fine for local testing and development purposes I guess

2024-08-01 08:57 UTC, akashvarun10 commented
Using environment variables in this manner for a development setup allows for easy launching and testing of the application and since this setup is only for development and not production, this approach should be fine for local testing and dev purposes

2024-08-01 11:58 UTC, amandesai01 commented
Yes I understand that, point being, we don't want to have 2 ways to setup `env` since it might be confusing. It's always better to rely on single source of truth.

2024-08-01 12:01 UTC, akashvarun10 commented
Okay, I have modified it . Can you check it now, I just changed it create env from env.example only

2024-08-01 12:08 UTC, amandesai01 commented
Code should not be copied over, directory should be mounted (so that code changes still work)
Something like this:
```yml
volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
```

2024-08-01 12:10 UTC, amandesai01 commented
Also, we don't want to hardcode env vars like you did in database. I ran this in detail through chatgpt, and found this:
```yml
   env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
```

2024-08-01 12:10 UTC, amandesai01 commented
Can you do something like this?

2024-08-01 12:11 UTC, akashvarun10 commented
Sure, I'll change it

2024-08-01 12:15 UTC, amandesai01 commented
Also, I am pretty curious about something and we would need to fix this (hopefully you can research on this):
Size of postgres image is 400mb
Size of Vidur codebase including node modules is 200mb
But, size of docker image: 2.4GB!!??

2024-08-01 12:21 UTC, amandesai01 commented
Also, please claim the issue and link PR

2024-08-01 12:24 UTC, akashvarun10 commented
> Also, I am pretty curious about something and we would need to fix this (hopefully you can research on this): Size of postgres image is 400mb Size of Vidur codebase including node modules is 200mb But, size of docker image: 2.4GB!!??

I'll check it out, it mostly for the layers of the containers, unused large files and node_modules i guess there is `.dockerignore`, I'll see what i can do

2024-08-01 12:24 UTC, akashvarun10 commented
> Also, please claim the issue and link PR

sure

2024-08-01 12:28 UTC, akashvarun10 commented
Also, is it fine if i change this to `NUXT_DB_HOST="db"`? Because in Docker providing it as localhost leads to internal communication error

2024-08-01 13:53 UTC, amandesai01 commented
Just request a review when you are ready.

2024-08-01 13:53 UTC, akashvarun10 commented
It's Done actually

2024-08-01 13:55 UTC, amandesai01 commented
We will also need to mount ./tmp dir since it will be used to store blobs in dev mode. I will do it.

2024-08-01 13:57 UTC, akashvarun10 commented
Sure, I'll try check how can we reduce the container size..

2024-08-01 14:21 UTC, akashvarun10 commented
Here I can submit a review but can't request it  I think you should add yourself on reviewer because i am not getting any option

2024-08-01 14:59 UTC, akashvarun10 commented
mounted temp storage for blob

2024-08-02 06:07 UTC, amandesai01 requested changes

2024-08-02 06:07 UTC, amandesai01 commented on Dockerfile
> +
```suggestion
FROM node:18.20-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install
```

2024-08-02 06:07 UTC, amandesai01 commented on docker-compose.yaml
> +  db_data:
```suggestion
version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${NUXT_DB_USER:-postgres}
      POSTGRES_PORT: ${NUXT_DB_PORT:-5432}
      POSTGRES_PASSWORD: ${NUXT_DB_PASSWORD:-postgrespw}
      POSTGRES_DB: ${NUXT_DB_DATABASE:-vidur}
    ports:
      - "5432:5432"
    volumes:
      - vidur_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vidur_app
    env_file:
      - .env
    environment:
      NUXT_DB_HOST: db
      NUXT_DB_PORT: ${NUXT_DB_PORT:-5432}
      NUXT_DB_USER: ${NUXT_DB_USER:-postgres}
      NUXT_DB_PASSWORD: ${NUXT_DB_PASSWORD:-postgrespw}
      NUXT_DB_DATABASE: ${NUXT_DB_DATABASE:-vidur}
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./src/public/tmp:/app/src/public/tmp  # Mounting the ./src/public/tmp directory for blob storage
    command: sh -c "yarn migration:apply && yarn dev"

volumes:
  vidur_data:
```

2024-08-02 06:07 UTC, amandesai01 commented on docs/README.md
> +Or Simply by Using Docker and Navigate to vidur then you can do as follows:
```suggestion
Or simply by using Docker Compose.
```

2024-08-02 06:07 UTC, amandesai01 commented on docs/README.md
> +docker compose up --build
```suggestion
docker compose up
```

2024-08-02 06:08 UTC, merged